### PR TITLE
Upgraded to latest angular-cli

### PR DESCRIPTION
**Pull request by royling**
- Upgraded angular-cli to 1.0.0-beta.30 (now named as @angular/cli)

Signed-off-by: Roy Ling <royling0024@gmail.com>

### CODE REVIEW

**Review by Shijir — APPROVED** [review]

**Comment by Shijir** [comment]
@royling thanks again for this contribution. Could please sign your commit? After that, I will merge this in.

**Comment by royling** [comment]
Done, amended the commit according to contributing notice, hope I am doing it right.

**Comment by Shijir** [comment]
@royling Almost perfect 😛 . You just need a space between your name and email:

```
Signed-off-by: Roy Ling<royling0024@gmail.com>
```
I recommend using `-s` flag to amend your commit so git appends your the sign in the bottow  automatically.

```
git commit --amend -s
```

**Comment by royling** [comment]
Now good to go, I think 😸

**Pull request merged**
